### ISSUE TITLE
Documentation revamp: migrate general docs from docs.zebedee.io to Mintlify codebase #1

### ISSUE THREAD

**Issue by andrerfneves** [zebedeeio/zbd-docs#1]
We intend to migrate all of the content of docs.zebedee.io to a new set of documentation pages hosted by Mintlify. We need someone to copy the contents of every one of the pages in the current docs.zebedee.io (not the API reference part yet, just the written docs) and port over to this codebase.

Start here: https://docs.zebedee.io/docs/quick-start

Basically, need to port over every page from inside https://docs.zebedee.io/docs/ over to this codebase. In individual pages. NOT the /api content which relates to the API Reference. That's a separate ticket.

The idea is to maintain the same content structure, just make it available within this new Mintlify kit/setup. The contents should be the same and use the best capabilities from Mintlify's systems.

**Comment by andrerfneves** [comment]
@Ashutosh-Bhadauriya looks like @nicktrn already finished all the work in that PR. I'm reviewing right now :S

**Comment by nicktrn** [comment]
Wouldn't normally do this, but the above user seems to tag all bounties he comes across. Surprisingly unresponsive too.

**Comment by andrerfneves** [comment]
Yeah that's what I've gathered given he claimed 3 bounties already and has submitted no PRs. Thanks for jumping in!

**Comment by Ashutosh-Bhadauriya** [comment]
@andrerfneves @nicktrn i had started to work on this and it was night here so couldn't respond, but cool

**Comment by andrerfneves** [comment]
Thanks @nicktrn for the great and quick turnaround here! I will have more and more of these kinds over the coming days and weeks :D

**Comment by nicktrn** [comment]
> I'll be back

**Comment by rishi-raj-jain** [comment]
@andrerfneves

> I will have more and more of these kinds over the coming days and weeks :D

I'd also love to be part of em!
