### ISSUE TITLE
Documentation revamp: migrate general API Reference endpoints from docs.zebedee.io to Mintlify codebase

### ISSUE THREAD

**Issue by andrerfneves** [zebedeeio/zbd-docs#2]
This is the sibling issue of https://github.com/andrerfneves/zbd-docs/issues/1.

We are migrating our content from our own documentation system built on docusaurus to one in Mintlify. We

We need someone to copy the contents of every one of the API Reference documents in the docs.zebedee.io THE API REFERENCE, and port over to this codebase.

Start here: https://docs.zebedee.io/api/intro

Basically, need to port over every page/endpoint from inside https://docs.zebedee.io/api/intro over to this codebase. In individual pages (as expected by Mintlifly)

The idea is to maintain the same content structure, just make it available within this new Mintlify kit/setup. The contents should be the same and use the best capabilities from Mintlify's systems

**Comment by rishi-raj-jain** [comment]
@andrerfneves I'd love to do this, @Ashutosh-Bhadauriya I see you already attempting the other issue. Can I take this one?

/attempt #2

**Comment by rishi-raj-jain** [comment]
it's in works! lmk if I should go ahead and complete it right away 🗡️ 

<img width="1476" alt="Screenshot 2023-08-07 at 4 54 43 PM" src="https://github.com/zebedeeio/zbd-docs/assets/46300090/a4795b5c-24ee-4108-a78e-32575338423f">

**Comment by andrerfneves** [comment]
Well I know the process should be to allow for the first person that attempts it. But it seems like you're really far into it already @rishi-raj-jain. @Ashutosh-Bhadauriya are you sure going to get to it?

**Comment by rishi-raj-jain** [comment]
Haha yeah, I can do this!

**Comment by andrerfneves** [comment]
@Ashutosh-Bhadauriya has claimed 3 of the bounties I've set out through Algora but he has yet to submit a PR so I'm unclear on how to proceed. 

@rishi-raj-jain if you want to take this one, let's go ahead and do this before the other ticket (https://github.com/zebedeeio/zbd-node/issues/3). But let's do it!

**Comment by Ashutosh-Bhadauriya** [comment]
@rishi-raj-jain go ahead

**Comment by andrerfneves** [comment]
Thanks @Ashutosh-Bhadauriya

**Comment by rishi-raj-jain** [comment]
Thanks @Ashutosh-Bhadauriya & @andrerfneves I'm on it!
