### ISSUE TITLE
Port over Replit guide to zbd.dev

### ISSUE THREAD

**Issue by andrerfneves** [zebedeeio/zbd-docs#30]
https://andreneves.xyz/p/bitcoin-payments-replit-zebedee-template-kit

**Comment by andrerfneves** [comment]
@nirgal-soft @stemperian

**Comment by nirgal-soft** [comment]
@andrerfneves i'm creating a new branch as we speak, i'll have this wrapped up today

**Comment by nirgal-soft** [comment]
see PR: https://github.com/zebedeeio/zbd-docs/pull/31
