### ISSUE TITLE
Miscellaneous changes/fixes to content copy/images

### ISSUE THREAD

**Issue by andrerfneves** [zebedeeio/zbd-docs#6]
## Tasks

**Change every instance of the term ZEBEDEE for ZBD:**
- `ZEBEDEE` becomes `ZBD`
- `ZEBEDEE API` becomes `ZBD API`
- Anything that is `ZEBEDEE ______` should become `ZBD ______`
- If something is `ZBD _____`, leave it as is
- If it's a name of a package or library (e.g. `zebedee-rust` crate, etc), do not change it
- `ZEBEDEE Developer Dashboard` should becomes `ZBD Dev Dashboard`

**Change logo to ZBD:**
- Dark Mode
![ZBD_LogotypeLight](https://github.com/zebedeeio/zbd-docs/assets/2574011/57592a08-c341-4176-963d-02cb5816e64f)

- Light Mode
![ZBD_LogotypeDark](https://github.com/zebedeeio/zbd-docs/assets/2574011/21293da0-da99-49d6-8b11-e967e8ac34f1)

**Understand and fix this crashing issue when clicking on the API References:**
- See video: https://www.dropbox.com/scl/fi/wo7hjmm86tnytfvdbjh0f/Screen-Recording-2023-08-13-at-8.25.13-PM.mov?rlkey=r2durehp2x0qtfy3ql8aur8ik&dl=0

**Change favicon to this new one:**
<img width="128" alt="favicon" src="https://github.com/zebedeeio/zbd-docs/assets/2574011/3477a13b-6b01-4e18-ba1f-8b2fe622ed9a">

**Change Menu Item from `Status` to `API Status`**

**Change Menu item from pointing to `status.zebedee.io` to point to `status.zbd.dev`** (domain is still recycling, don't worry if this URL doesn't render yet)

**Comment by andrerfneves** [comment]
@rishi-raj-jain thought this one was a good one for you to pick up!

**Comment by rishi-raj-jain** [comment]
I'm on it!

**Comment by andrerfneves** [comment]
I'm adding the VIDEO piece above right now

**Comment by rishi-raj-jain** [comment]
Should the docs link that have docs.zebedee.io also change to docs.zbd.io?

**Comment by andrerfneves** [comment]
`docs.zbd.dev` please. But YES, let's make that change too. Thanks for catching that

**Comment by rishi-raj-jain** [comment]
<img width="520" alt="Screenshot 2023-08-14 at 8 59 29 AM" src="https://github.com/zebedeeio/zbd-docs/assets/46300090/972121f1-099a-4768-9de9-f726523d96b0">
Shall change this to Dev Dashboard?

**Comment by andrerfneves** [comment]
Yes makes sense to me.

**Comment by rishi-raj-jain** [comment]
What do you think about help/api.zebedee.io changes?

**Comment by andrerfneves** [comment]
For now let's keep those as is as they are external entities. We'll migrate those later 👍
