### ISSUE TITLE
Change to sidebar interface for navigation and reorganize pages

### ISSUE THREAD

**Issue by nirgal-soft** [zebedeeio/zbd-docs#8]
# Tasks
### Switch from Tabbed to Sidebar Interface
Mintlify provides a sidebar navigation option. We need you to change our current tabbed interface to this sidebar interface.

**Current (Tabbed Interface)**:
  ![Old Screenshot](https://github.com/zebedeeio/zbd-docs/assets/25555001/bd705eeb-ac5b-4af3-a01b-4d24062657da)

**Desired (Sidebar Interface)**:
  ![New Screenshot](https://github.com/zebedeeio/zbd-docs/assets/25555001/afd84ebc-4e18-42a9-a1bc-2232c3764fb6)

### Pages Redirect Incorrectly
There is a bug where certain pages in the sidebar are only visible when viewed locally and are redirecting to the wrong page (the `Quick Start` page). They should navigate to their correct routes. The affected pages are:
- Overview
- Authentication
- Error handling
- SDKs
- Resources

**Local Environment (Correct)**
  ![Local Screenshot](https://github.com/zebedeeio/zbd-docs/assets/25555001/c1e1578c-d49e-4156-be6b-faebbb5afd44)

**Web Deployment (Incorrect)**
  ![Web Screenshot](https://github.com/zebedeeio/zbd-docs/assets/25555001/3eeb721c-72cb-4c27-a0d6-a975d912f0ca)

### Move Specified Pages to New Section
Create a new section called "Knowledge Base" in the sidebar and move the following pages to it:
- The Bitcoin Lightning Network Revolutionizes Payments
- Glossary
- All pages under `ZBD API`
- All pages under `Guides/Miscellaneous`
- All pages under `Guides/Community`

Please also remove the Miscellaneous and Community sections from the navigation.

### Modify Sections
Make the following changes to the Documentation page:
- Remove the `Overview` section and rename the `Quick Start` page to `Overview`.
- Combine the remaining Guides and Walkthrough pages into a single "Guides" section.

### Use Specific Icons from Content Library
Update the current icons with the new ones provided in our content library. Refer to the screenshot below for specifics.
![Icons Screenshot](https://github.com/zebedeeio/zbd-docs/assets/25555001/afd84ebc-4e18-42a9-a1bc-2232c3764fb6)

**Comment by andrerfneves** [comment]
@rishi-raj-jain care for another one? :D

**Comment by rishi-raj-jain** [comment]
@andrerfneves Would love to see the bounty award in for this!

**Comment by rishi-raj-jain** [comment]
Thank you, @andrerfneves!
